modLoader="javafml"
loaderVersion="[28,)"
issueTrackerURL="http://my.issue.tracker/"

[[mods]]
modId="firelib2"
version="${file.jarVersion}"
displayName="Fire Library 2"
updateJSONURL="http://myurl.me/"
displayURL="http://example.com/"
logoFile=""
credits=""
authors="FireBall1725"
description='''
Library mod for all FireBall1725 mods
'''

[[dependencies.firelib2]]
    modId="forge"
    mandatory=true
    versionRange="[28,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.firelib2]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.14.4]"
    ordering="NONE"
    side="BOTH"
